name: Create a milestone issue
on:
  push:
    branches: ['master']
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        uses: josStorer/get-current-time@v2
        id: current-date
        with:
          format: MMM-DD-YYYY
      - name: Relay date 
        run: echo ${{ steps.current-date.outputs.time }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          milestone: ${{ steps.current-date.outputs.time }} ADF Website Release