name: Create a milestone issue
on:
  push:
    branches: ['master']
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        uses: josStorer/get-current-time@v2
        id: current-date
        with:
          format: MMM-DD-YYYY
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          filename: .github/MILESTONE_TEMPLATE.md
          milestone: ${{ steps.current-date.outputs.time }} ADF Website Release