lname: Milestone content
on:
  push:
    branches:
      - master

permissions:
  contents: read
  issues: write 

jobs:
  add-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          script: |
            // Get all milestones
            const {data: milestones} = await github.rest.issues.listMilestones({
              repo: context.repo.repo,
              owner: context.repo.owner,
              state: 'open',
              sort: 'due_on',
              per_page: 100
            })

            if (!milestones.length) {
              console.log('There are no open milestones in this repo, ending run.')
              return
            }

            // Constants
            const currentDate = new Date(Date.now())
            const monthNames = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
            const currentMonth = monthNames[currentDate.getMonth()]
            const currentDay = currentDate.getDate()
            const currentYear = currentDate.getFullYear()
            const milestoneIssueList = []

            // Get current milestone
            for (const milestone of milestones) {
              if (milestone.due_on && new Date(milestone.due_on) > currentDate) {

                // Get list of Issues in the current milestone
                let {data: milestoneIssues} = await github.rest.issues.listForRepo({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  milestone: milestone.number,
                  state: 'closed',
                  assignee: '*',
                  direction: 'desc',
                  per_page: 100
                })

                // Get list of PRs in the current milestone
                let {data: milestonePrs} = await github.rest.pulls.list({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  state: 'closed',
                  direction: 'desc',
                  per_page: 100
                })

                // Create list items for each issue associated with the milestone
                // TODO: Remove ","?
                for (let milestoneIssue of milestoneIssues) {
                  milestoneIssueList.push("</li><li>#" + milestoneIssue.number + ": " + milestoneIssue.title)
                }

                // List PRs for each issue associated with the milestone
                // TODO: Remove ","?
                for (let milestonePr of milestonePrs) {
                  if (milestonePr.milestone && milestonePr.merged_at) {
                    if (milestonePr.milestone.number === milestone.number) {
                      milestoneIssueList.push("</li><li>#" + milestonePr.number + ": " + milestonePr.title)
                    }
                  }
                  
                }
              }
            }

            // Create the issue
            await github.rest.issues.create({
              repo: context.repo.repo,
              owner: context.repo.owner,
              assignees: ['geospatialem'],
              labels: ['Documentation', '6 - Ready to Deploy'],
              title: "Docs: " + currentMonth + " " + currentDay + " Release Update 🚀",
              body: `### Description
              This week's updates include:

              <ul>` +
                milestoneIssueList
              + `</li></ul>


              More info: [Milestone: ` + currentMonth + `-` + currentDay + `-` + currentYear + `](../issues?q=milestone%3A%22` + currentMonth + `-` + currentDay + `-` + currentYear + `+AFD+Website+Release%22+is%3Aclosed)`
            })

            return            