name: Milestone content
on:
  push:
    branches:
      - master
jobs:
  add-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const {data: milestones} = await github.rest.issues.listMilestones({
              repo: context.repo.repo
              state: 'open',
              sort: 'due_on',
              per_page: 100,
              direction: farthest ? 'desc' : 'asc'
            })

            console.log(data.milestones);

            if (!milestones.length) {
              console.log('There are no open milestones in this repo, ending run.')
              return
            }

            const currentDate = new Date(Date.now())
            for (const milestone of milestones) {
              if (milestone.due_on && new Date(milestone.due_on) > currentDate) {
                await github.rest.issues.update({
                  repo: context.repo.repo,
                  issue_number,
                  milestone: milestone.number
                })
                setOutput('milestone', milestone)
                return
              }
            }            