name: Milestone content
on:
  push:
    branches:
      - master

permissions:
  contents: read
  issues: write 

jobs:
  add-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          script: |
            const {data: milestones} = await github.rest.issues.listMilestones({
              repo: context.repo.repo,
              owner: context.repo.owner,
              state: 'open',
              sort: 'due_on',
              per_page: 100
            })

            if (!milestones.length) {
              console.log('There are no open milestones in this repo, ending run.')
              return
            }

            const currentDate = new Date(Date.now())
            for (const milestone of milestones) {
              console.log(milestone)
              if (milestone.due_on && new Date(milestone.due_on) > currentDate) {
                await github.rest.issues.update({
                  repo: context.repo.repo,
                  owner: context.repo.owner,
                  issue_number,
                  milestone: milestone.number
                })
                setOutput('milestone', milestone)
                return
              }
            }   

            # Get list of issues in milestone
            # const {data.milestoneIssues} = await github.rest.issues.listForRepo({
            #   owner: context.repo.owner,
            #   repo: context.repo.repo,
            #   milestone: 1
            # })

            # await github.rest.issues.create({
            #   repo: context.repo.repo,
            #   owner: context.repo.owner,
            #   title: 'Release Update'
            # })

            # return            