name: Milestone content
on:
  push:
    branches:
      - master
jobs:
  add-content:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.github_token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/github-script@v6
        with:
          script: |
            const {data: milestones} = await github.rest.issues.listMilestones({
              repo: context.repo.repo,
              owner: context.repo.owner,
              state: 'open',
              sort: 'due_on',
              per_page: 100
            })

            if (!milestones.length) {
              console.log('There are no open milestones in this repo, ending run.')
              return
            }

            const currentDate = new Date(Date.now())
            for (const milestone of milestones) {
              if (milestone.due_on && new Date(milestone.due_on) > currentDate) {
                await github.rest.issues.update({
                  repo: context.repo.repo,
                  owner: context.repo.owner,
                  issue_number,
                  milestone: milestone.number
                })
                setOutput('milestone', milestone)
                # return
              }
            }

            # Get list of issues in milestone
            const {data.milestoneIssues} = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              milestone: 1
            })

            github.rest.issues.create({
              repo: context.repo.repo,
              owner: context.repo.owner,
              title: 'Docs: Release Update',
              assignees: ['geospatialem'],
              milestone: 2,
              labels: ['Documentation', '6 - Ready to Deploy'],
              body: milestoneIssues
            })

            return            