name: Create a milestone issue
on:
  push:
    branches: ['master']
permissions:
  contents: read
  issues: write 
jobs:
  get-date:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        uses: josStorer/get-current-time@v2
        id: current-date
        with:
          format: MMM-DD-YYYY
      - name: Relay date 
        run: echo ${{ steps.current-date.outputs.time }}
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}